#!/bin/bash

if [ $# -eq 0 ]; then
    FILE='cpsc490-prospectus.md';
elif [ "$1" == "clean" ]; then
    rm 'cpsc490-prospectus.pdf' &&
        exit 0;
else
    FILE="$1";
fi

OUTPUT="$(basename "$FILE" .md)".pdf 

pandoc -o "$OUTPUT" "$FILE" &&
    open "$OUTPUT"

if [ $# -eq 0 ]; then
    cp cpsc490-prospectus.pdf ~/Dropbox/Public/;
fi
